name = "minecraft-creative-create-1"
author = "mikepea"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a9c23a9dc7a85038b7b8d88ef8bea6e15973b87cbe95472b5eb8bc301e686036"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
