name = "minecraft-creative-create-1"
author = "mikepea"
version = "0.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "532ffb6ddfdaf9d88517216f13fd876b8af3d80947ccf8a90540eda76aeedbb2"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
